diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
ubser.name=Phrs467
user.email=phrs467@gmail.com
user.name=PedroH
init.defaultbranch=main
http.sslverify=false
http.postbuffer=20k
credential.https://developer1.alfredonasser.com.br.provider=generic
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/Phrs467/AjudaQiWeb.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
